language: python
dist: trusty
sudo: disabled

python: 3.6
env:
 - TOX_ENV=codecov
 - TOX_ENV=py35
 - TOX_ENV=py36
 - TOX_ENV=integration_tests
 - TOX_ENV=lint
 - TOX_ENV=mypy
 - TOX_ENV=docs
install:
 - pip install tox
script:
 - tox -e $TOX_ENV
