language: python
dist: trusty
sudo: disabled

cache: pip

python: 3.6
env:
 - TOX_ENV=codecov
 - TOX_ENV=integration_tests
 - TOX_ENV=py36
 - TOX_ENV=lint
 - TOX_ENV=mypy
 - TOX_ENV=docs

matrix:
    include:
        - python: 3.5-dev
          env: TOX_ENV=py35

install:
 - pip install tox

script:
 - tox -e $TOX_ENV
